/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTransformRouteImport } from './routes/_authenticated/app.transform'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppLoadRouteImport } from './routes/_authenticated/app.load'
import { Route as AuthenticatedAppFindRouteImport } from './routes/_authenticated/app.find'
import { Route as AuthenticatedAppExtractRouteImport } from './routes/_authenticated/app.extract'
import { Route as AuthenticatedAppAnalyzeRouteImport } from './routes/_authenticated/app.analyze'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTransformRoute =
  AuthenticatedAppTransformRouteImport.update({
    id: '/transform',
    path: '/transform',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLoadRoute = AuthenticatedAppLoadRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFindRoute = AuthenticatedAppFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExtractRoute = AuthenticatedAppExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyzeRoute = AuthenticatedAppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/app/extract': typeof AuthenticatedAppExtractRoute
  '/app/find': typeof AuthenticatedAppFindRoute
  '/app/load': typeof AuthenticatedAppLoadRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/transform': typeof AuthenticatedAppTransformRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/app/extract': typeof AuthenticatedAppExtractRoute
  '/app/find': typeof AuthenticatedAppFindRoute
  '/app/load': typeof AuthenticatedAppLoadRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/transform': typeof AuthenticatedAppTransformRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/_authenticated/app/extract': typeof AuthenticatedAppExtractRoute
  '/_authenticated/app/find': typeof AuthenticatedAppFindRoute
  '/_authenticated/app/load': typeof AuthenticatedAppLoadRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/transform': typeof AuthenticatedAppTransformRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/app'
    | '/api/chat'
    | '/app/analyze'
    | '/app/extract'
    | '/app/find'
    | '/app/load'
    | '/app/settings'
    | '/app/transform'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/chat'
    | '/app/analyze'
    | '/app/extract'
    | '/app/find'
    | '/app/load'
    | '/app/settings'
    | '/app/transform'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/app'
    | '/api/chat'
    | '/_authenticated/app/analyze'
    | '/_authenticated/app/extract'
    | '/_authenticated/app/find'
    | '/_authenticated/app/load'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/transform'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transform': {
      id: '/_authenticated/app/transform'
      path: '/transform'
      fullPath: '/app/transform'
      preLoaderRoute: typeof AuthenticatedAppTransformRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/load': {
      id: '/_authenticated/app/load'
      path: '/load'
      fullPath: '/app/load'
      preLoaderRoute: typeof AuthenticatedAppLoadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/find': {
      id: '/_authenticated/app/find'
      path: '/find'
      fullPath: '/app/find'
      preLoaderRoute: typeof AuthenticatedAppFindRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/extract': {
      id: '/_authenticated/app/extract'
      path: '/extract'
      fullPath: '/app/extract'
      preLoaderRoute: typeof AuthenticatedAppExtractRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analyze': {
      id: '/_authenticated/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AuthenticatedAppAnalyzeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyzeRoute: typeof AuthenticatedAppAnalyzeRoute
  AuthenticatedAppExtractRoute: typeof AuthenticatedAppExtractRoute
  AuthenticatedAppFindRoute: typeof AuthenticatedAppFindRoute
  AuthenticatedAppLoadRoute: typeof AuthenticatedAppLoadRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTransformRoute: typeof AuthenticatedAppTransformRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyzeRoute: AuthenticatedAppAnalyzeRoute,
  AuthenticatedAppExtractRoute: AuthenticatedAppExtractRoute,
  AuthenticatedAppFindRoute: AuthenticatedAppFindRoute,
  AuthenticatedAppLoadRoute: AuthenticatedAppLoadRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTransformRoute: AuthenticatedAppTransformRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
