// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      approvals: {
        Row: {
          id: string;
          customer_id: string;
          property_id: string;
          stage: Database["public"]["Enums"]["approval_stage"];
          status: Database["public"]["Enums"]["approval_status"];
          approved_by: string | null;
          approved_at: string | null;
          comments: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          property_id: string;
          stage: Database["public"]["Enums"]["approval_stage"];
          status?: Database["public"]["Enums"]["approval_status"];
          approved_by?: string | null;
          approved_at?: string | null;
          comments?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          property_id?: string;
          stage?: Database["public"]["Enums"]["approval_stage"];
          status?: Database["public"]["Enums"]["approval_status"];
          approved_by?: string | null;
          approved_at?: string | null;
          comments?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "approvals_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "approvals_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "approvals_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
        ];
      };
      commissions: {
        Row: {
          id: string;
          sales_staff_id: string;
          customer_id: string | null;
          property_id: string | null;
          rate_percent: number;
          amount: number;
          status: Database["public"]["Enums"]["commission_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          sales_staff_id: string;
          customer_id?: string | null;
          property_id?: string | null;
          rate_percent?: number;
          amount: number;
          status?: Database["public"]["Enums"]["commission_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          sales_staff_id?: string;
          customer_id?: string | null;
          property_id?: string | null;
          rate_percent?: number;
          amount?: number;
          status?: Database["public"]["Enums"]["commission_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "commissions_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "commissions_sales_staff_id_fkey";
            columns: ["sales_staff_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "commissions_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
        ];
      };
      customers: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          phone: string | null;
          email: string | null;
          assigned_sales_owner: string | null;
          referral_source: string | null;
          lead_status: Database["public"]["Enums"]["lead_status"];
          kyc_status: Database["public"]["Enums"]["verification_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          phone?: string | null;
          email?: string | null;
          assigned_sales_owner?: string | null;
          referral_source?: string | null;
          lead_status?: Database["public"]["Enums"]["lead_status"];
          kyc_status?: Database["public"]["Enums"]["verification_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          phone?: string | null;
          email?: string | null;
          assigned_sales_owner?: string | null;
          referral_source?: string | null;
          lead_status?: Database["public"]["Enums"]["lead_status"];
          kyc_status?: Database["public"]["Enums"]["verification_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "customers_assigned_sales_owner_fkey";
            columns: ["assigned_sales_owner"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      documents: {
        Row: {
          id: string;
          customer_id: string;
          property_id: string | null;
          doc_type: Database["public"]["Enums"]["document_type"];
          file_name: string;
          file_url: string;
          uploaded_by: string | null;
          upload_date: string;
          verification_status: Database["public"]["Enums"]["verification_status"];
          verifier_notes: string | null;
          verified_by: string | null;
          verified_at: string | null;
        };
        Insert: {
          id?: string;
          customer_id: string;
          property_id?: string | null;
          doc_type: Database["public"]["Enums"]["document_type"];
          file_name: string;
          file_url: string;
          uploaded_by?: string | null;
          upload_date?: string;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          verifier_notes?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
        };
        Update: {
          id?: string;
          customer_id?: string;
          property_id?: string | null;
          doc_type?: Database["public"]["Enums"]["document_type"];
          file_name?: string;
          file_url?: string;
          uploaded_by?: string | null;
          upload_date?: string;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          verifier_notes?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "documents_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "documents_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "documents_verified_by_fkey";
            columns: ["verified_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      installment_plans: {
        Row: {
          id: string;
          property_id: string;
          customer_id: string;
          total_amount: number;
          num_installments: number;
          start_date: string;
          frequency: string;
          penalty_rate_percent: number;
          penalty_grace_days: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          property_id: string;
          customer_id: string;
          total_amount: number;
          num_installments: number;
          start_date?: string;
          frequency?: string;
          penalty_rate_percent?: number;
          penalty_grace_days?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          property_id?: string;
          customer_id?: string;
          total_amount?: number;
          num_installments?: number;
          start_date?: string;
          frequency?: string;
          penalty_rate_percent?: number;
          penalty_grace_days?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "installment_plans_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "installment_plans_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
        ];
      };
      installments: {
        Row: {
          id: string;
          plan_id: string;
          seq_no: number;
          due_date: string;
          amount: number;
          status: Database["public"]["Enums"]["payment_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          plan_id: string;
          seq_no: number;
          due_date: string;
          amount: number;
          status?: Database["public"]["Enums"]["payment_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          plan_id?: string;
          seq_no?: number;
          due_date?: string;
          amount?: number;
          status?: Database["public"]["Enums"]["payment_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "installments_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "installment_plans";
            referencedColumns: ["id"];
          },
        ];
      };
      lead_notes: {
        Row: {
          id: string;
          customer_id: string;
          author_id: string | null;
          note: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          author_id?: string | null;
          note: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          author_id?: string | null;
          note?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lead_notes_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_notes_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          customer_id: string;
          title: string;
          message: string;
          type: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          title: string;
          message: string;
          type?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          title?: string;
          message?: string;
          type?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          id: string;
          customer_id: string;
          property_id: string;
          installment_id: string | null;
          amount: number;
          due_date: string | null;
          paid_date: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          payment_mode: Database["public"]["Enums"]["payment_mode"] | null;
          receipt_reference: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          property_id: string;
          installment_id?: string | null;
          amount: number;
          due_date?: string | null;
          paid_date?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          payment_mode?: Database["public"]["Enums"]["payment_mode"] | null;
          receipt_reference?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          property_id?: string;
          installment_id?: string | null;
          amount?: number;
          due_date?: string | null;
          paid_date?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          payment_mode?: Database["public"]["Enums"]["payment_mode"] | null;
          receipt_reference?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_installment_id_fkey";
            columns: ["installment_id"];
            isOneToOne: false;
            referencedRelation: "installments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          full_name: string | null;
          email: string | null;
          phone: string | null;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          name: string;
          location: string;
          description: string | null;
          cover_image_url: string | null;
          layout_image_url: string | null;
          type_mix: Database["public"]["Enums"]["project_type_mix"];
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          location: string;
          description?: string | null;
          cover_image_url?: string | null;
          layout_image_url?: string | null;
          type_mix?: Database["public"]["Enums"]["project_type_mix"];
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          location?: string;
          description?: string | null;
          cover_image_url?: string | null;
          layout_image_url?: string | null;
          type_mix?: Database["public"]["Enums"]["project_type_mix"];
          created_at?: string;
        };
        Relationships: [];
      };
      properties: {
        Row: {
          id: string;
          project_id: string;
          property_type: Database["public"]["Enums"]["property_type"];
          code: string;
          price: number;
          status: Database["public"]["Enums"]["property_status"];
          customer_id: string | null;
          cover_image_url: string | null;
          size_sqyd: number | null;
          facing: Database["public"]["Enums"]["facing_direction"] | null;
          is_corner: boolean | null;
          road_width_ft: number | null;
          tower: string | null;
          floor_number: number | null;
          bhk: string | null;
          carpet_area_sqft: number | null;
          builtup_area_sqft: number | null;
          parking_slots: number | null;
          amenities: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          property_type: Database["public"]["Enums"]["property_type"];
          code: string;
          price: number;
          status?: Database["public"]["Enums"]["property_status"];
          customer_id?: string | null;
          cover_image_url?: string | null;
          size_sqyd?: number | null;
          facing?: Database["public"]["Enums"]["facing_direction"] | null;
          is_corner?: boolean | null;
          road_width_ft?: number | null;
          tower?: string | null;
          floor_number?: number | null;
          bhk?: string | null;
          carpet_area_sqft?: number | null;
          builtup_area_sqft?: number | null;
          parking_slots?: number | null;
          amenities?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          property_type?: Database["public"]["Enums"]["property_type"];
          code?: string;
          price?: number;
          status?: Database["public"]["Enums"]["property_status"];
          customer_id?: string | null;
          cover_image_url?: string | null;
          size_sqyd?: number | null;
          facing?: Database["public"]["Enums"]["facing_direction"] | null;
          is_corner?: boolean | null;
          road_width_ft?: number | null;
          tower?: string | null;
          floor_number?: number | null;
          bhk?: string | null;
          carpet_area_sqft?: number | null;
          builtup_area_sqft?: number | null;
          parking_slots?: number | null;
          amenities?: string[] | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "properties_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "properties_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      site_visits: {
        Row: {
          id: string;
          customer_id: string;
          project_id: string;
          property_id: string | null;
          scheduled_date: string;
          assigned_staff: string | null;
          status: Database["public"]["Enums"]["site_visit_status"];
          outcome_notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          project_id: string;
          property_id?: string | null;
          scheduled_date: string;
          assigned_staff?: string | null;
          status?: Database["public"]["Enums"]["site_visit_status"];
          outcome_notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          project_id?: string;
          property_id?: string | null;
          scheduled_date?: string;
          assigned_staff?: string | null;
          status?: Database["public"]["Enums"]["site_visit_status"];
          outcome_notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "site_visits_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "site_visits_assigned_staff_fkey";
            columns: ["assigned_staff"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "site_visits_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "site_visits_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          project_id: string | null;
          customer_id: string | null;
          assigned_to: string | null;
          status: Database["public"]["Enums"]["task_status"];
          due_date: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          project_id?: string | null;
          customer_id?: string | null;
          assigned_to?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          due_date?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          project_id?: string | null;
          customer_id?: string | null;
          assigned_to?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          due_date?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      approval_stage:
        "booking" | "legal_verification" | "finance_clearance" | "registration" | "possession";
      approval_status: "pending" | "approved" | "rejected";
      commission_status: "pending" | "paid";
      document_type:
        | "sale_agreement"
        | "title_deed"
        | "approval_certificate"
        | "id_proof"
        | "occupancy_certificate"
        | "kyc"
        | "other";
      facing_direction: "east" | "west" | "north" | "south";
      lead_status: "new" | "contacted" | "site_visit" | "booked" | "sold";
      payment_mode: "cash" | "cheque" | "bank_transfer" | "upi" | "card" | "other";
      payment_status: "paid" | "pending" | "overdue";
      project_type_mix: "plots" | "flats" | "both";
      property_status: "available" | "blocked" | "sold";
      property_type: "plot" | "flat";
      site_visit_status: "scheduled" | "completed" | "cancelled" | "no_show";
      task_status: "todo" | "in_progress" | "done";
      user_role: "customer" | "sales" | "finance" | "legal" | "admin";
      verification_status: "pending" | "verified" | "rejected";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      approval_stage: [
        "booking",
        "legal_verification",
        "finance_clearance",
        "registration",
        "possession",
      ],
      approval_status: ["pending", "approved", "rejected"],
      commission_status: ["pending", "paid"],
      document_type: [
        "sale_agreement",
        "title_deed",
        "approval_certificate",
        "id_proof",
        "occupancy_certificate",
        "kyc",
        "other",
      ],
      facing_direction: ["east", "west", "north", "south"],
      lead_status: ["new", "contacted", "site_visit", "booked", "sold"],
      payment_mode: ["cash", "cheque", "bank_transfer", "upi", "card", "other"],
      payment_status: ["paid", "pending", "overdue"],
      project_type_mix: ["plots", "flats", "both"],
      property_status: ["available", "blocked", "sold"],
      property_type: ["plot", "flat"],
      site_visit_status: ["scheduled", "completed", "cancelled", "no_show"],
      task_status: ["todo", "in_progress", "done"],
      user_role: ["customer", "sales", "finance", "legal", "admin"],
      verification_status: ["pending", "verified", "rejected"],
    },
  },
} as const;
